import "./globals.css";

export const metadata = {
  title: "Todomate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body >{children}</body>
    </html>
  );
}
